### ISSUE TITLE
Make screen after "find me" timeout clearer.

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#119]
No one, including teacher, knew what to do when "find me" timed out. The screen just confused them all.

I don't have a screen shot of the screen right now, but maybe it should just go back to the step 1, step 2 connect screen that they are familiar with.

**Comment by tasota** [comment]
This is what happens when we time out before actually connecting to Flutter: 
![screenshot_2017-04-05-13-16-02](https://cloud.githubusercontent.com/assets/9115672/24718013/7009a61c-1a02-11e7-8caa-069b76bcca28.png)

This is what happens between "find me" and loading to Sensors tab (I know we also still need to implement #98, which is related to this one):
![screenshot_2017-04-05-13-19-55](https://cloud.githubusercontent.com/assets/9115672/24718064/a3dab22e-1a02-11e7-9086-88ed7b06fbfb.png)

**Comment by mo11yj** [comment]
I added a dialog explaining that the kindle and flutter were unable to connect. When the user taps Try Again, I think it should go to the "Link Your Flutter" page (https://zpl.io/Z1TFY7y)

Zeplin link for new screen: https://zpl.io/26R7EM

![screen shot 2017-04-15 at 8 23 24 pm](https://cloud.githubusercontent.com/assets/25698542/25072099/ecb595c8-2294-11e7-9f80-90a4f3d23481.png)

**Comment by tasota** [comment]
More info on generic error messages can be found in the BLEError class:

```
package com.bluecreation.melodysmart;

public class BLEError {

...
    public static enum Type {
        NO_ERROR("no error"),
        AUTHENTICATION_ERROR("authentication error: check bonding information on your phone and on Melody Smart. Try to remove bond information on both sides and reconnect."),
        TIMEOUT_ERROR("timeout error: connection died. Check your Melody Smart device is in range and charged"),
        REMOTE_DISCONNECTION("remote device terminated connection."),
        UNKNOWN_ERROR("unknown error");

        private String mMessage;

        private Type(String message) {
            this.mMessage = message;
        }

        public String getMessage() {
            return this.mMessage;
        }
    }
}
```

Still need to look up timeout length
