### ISSUE TITLE
add development version for non-store app versions

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#139]
See Emily's comment from #134:

development version usually has the same number as the previous release version which makes it hard to tell apart when we have it on a kindle. Would it be possible to increment the version after a release and mark it with a "d" until it's ready for the next release?

**Comment by pdille** [comment]
@tasota 
There's no way to automate this and it's on us to remember doing it. I'm in git issue clearing mode and there really is no point in having this open. While you normally do the releases, I nominate myself to ensure we are adhering to it. As a reminder:

1. When we cut a release branch, we increment the version like we normally do. For example, the next release we bump up to 1.0.4
2. Immediately create a commit to master changing the version to 1.0.5d (yes, two version change commits in a row, but the version string with a 'd' signifies the start of a new work cycle in master)
... Time passes ...
3. Upon the next release we remove the 'd', cut and create release branch.
4. The next commit to master is changing the version to 1.0.6d
5. So on and so forth.

**Comment by tasota** [comment]
OK but I think we should discuss this before we close again.

**Comment by jenncross** [comment]
Not sure how applicable this is however...

Chris had a way that when we did builds of CREATE Lab Visual Programmer (with ANT) so it would automatically pull in the commit count from the repository as the last set of digits of the version number. So for example we would have a version 1.12.783  where the "1" was for very large version changes, 12 was the small version changes, and 783 was the repository commit number. Which was great, because that last number told us everything about what version the teacher was using. 

If this sort of thing could be worked in, it won't add the development "d" but it would perhaps distinguish between subtle version differences and let us better match report issues with the code state.

**Comment by tasota** [comment]
> Chris had a way that when we did builds of CREATE Lab Visual Programmer (with ANT) so it would automatically pull in the commit count from the repository as the last set of digits of the version number. So for example we would have a version 1.12.783 where the "1" was for very large version changes, 12 was the small version changes, and 783 was the repository commit number. Which was great, because that last number told us everything about what version the teacher was using.

I really like this. Although it won't easily designate what is development vs. production, I think we should consider implementing something like this.

**Comment by pdille** [comment]
Sure, if you want finer grained look at what the exact version of the code is being run, what Chris did is the way to do it. In general, version changes adhere to the just what you said, "A.B.C" where A is a major change occurring, which often means breaking backwards compatibility, significant interface overhauls, etc. B is then a moderate change to the software (small features added, important bug fixes, etc). Lastly, C is minor bug fixes. We're not really adhering to this scheme, but that's fine. The point is keeping track.

What I was suggesting was a trivial approach to let us know internally what we are using. Is this what the teachers have from the store or is it a dev version? Just simple as that. We can take it a step further though and say, ah, we are using a dev version, but what exact dev version is this? That's certainly better (and what we should strive for) but isn't something we can immediately do right now.

To actually designate that it's dev or not using Chris's approach, we can just make the store release end with a 0 and all devs versions be a commit #. For example:

We just released 1.1.0 to the store. Internally, we work on the next version and this becomes 1.1.424, then 1.1.428, etc, etc. Later we release the next version to the store and it becomes 1.2.0. The cycle continues. Easy enough. We know what's dev and not and we know what dev version we are looking at.

We always have to manually change the build file to the next version, so that process stays the same. Getting the commit # to happen automatically, *but not when you build the release one*, is the new bit we need to figure out. Surely doable though.

**Comment by pdille** [comment]
Alright, I was intrigued and went ahead implementing this. :) Tasota saw and was pleased. Haha.

Dev versions will say: dev-latestGitHash (where latestGitHash are first 7 characters of the last git commit)
Release versions will say: vX.Y.Z (where the values are based on MAJOR.MINOR.REVISION)

**Comment by tasota** [comment]
I wanted to add stickers from the bus but can't find that option from their app

**Comment by tasota** [comment]
But nevertheless, I'm excited to start using this from now on
