### ISSUE TITLE
stop requesting sensor values (protocol command 'r') while in data tab

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#147]
Sensor values are not being displayed while we are on the Data tab, so we could probably hold off requesting those values until we go back to sensors/robots.

**Comment by pdille** [comment]
Do you still see this? I was double checking just now and I don't see those requests...

**Comment by tasota** [comment]
We might have just fixed this an hour ago with our debugging

**Comment by pdille** [comment]
So that's why I bring it up. I don't see it with and without that fix.

**Comment by SteveFulton95** [comment]
I never noticed this issue until I just pulled from master. I have a BaseSensorReadingActivity that handles reading sensor values. I override onPause and stop the sensor reading within that method.  I double checked and the only Activities that extend BaseSensorReadingActivity are the Sensor and Robot activities.  Maybe that onPause method is no longer getting called? I haven't looked into that yet. Maybe in a recent commit, that onPause method was overridden and super.onPause() was never called? I'll check now instead of just talking about it.

**Comment by SteveFulton95** [comment]
Now I am experiencing what @pdille experienced. I do not see the problem.

**Comment by tasota** [comment]
I think Paul and I were on the fence the other day to make this "cant be replicated"

There were some changes also made to BaseSensorReadingActivity from paul (which calls to stop the readings) and I also made some changes on my branch right now to avoid null pointer.

If this is still a problem I don't think it's from onPause but rather on opening one of the dialogs. Let me know if you find something when you take a look now. Otherwise, I can go back and check as well.

**Comment by tasota** [comment]
Alright, I'll check and close shortly, I'm guessing.
