### ISSUE TITLE
Don't scale simulate data numbers

### ISSUE THREAD

**Issue by lczito** [CMU-CREATE-Lab/flutter-app-android#156]
Right now, the simulate data numbers scale based on sensors, meaning that students get three different numbers when sliding the slider. It is confusing. Instead, can we just have all three sensors have the same number (even the distance sensor)?

**Comment by tasota** [comment]
This is feasible but will be based on the currently set sensor type. On my phone so I can't find it but there's also an issue entered about changing the scale after changing sensor type (for the output) so that is also related to this I would say (or at least would be nice to have both done at once)

**Comment by tasota** [comment]
I was referring to #137 above.

In our ideal case, all of this will be seamless to the user. The sensor type should not be affecting the  value range of the assigned links. When the sensor type changes, the links will update automatically. And when we begin simulating the values, we should either A) scale the "simulated" value back to what the sensor type is, or B) update the links to be at a normal (0-100) range again. I lean towards method A because it doesn't involve sending more commands to the board.

**Comment by jenncross** [comment]
This should be resolved by having three separate sliders. Use solution from #208
