### ISSUE TITLE
Add border to the split LED colored circles

### ISSUE THREAD

**Issue by pdille** [CMU-CREATE-Lab/flutter-app-android#186]
This is critical for the color white but might be easier to just always have a border? Maybe not.

**Comment by tasota** [comment]
@SteveFulton95 I think this was as simple as just modifying the resources to include a border on the shapes, but double-check that those resources aren't being used elsewhere.

This was assigned to me originally because I worked on the half-circle display (it involves cutting shapes with other shapes) but you shouldn't have to touch any of that to get the borders working.
