### ISSUE TITLE
Add expected duration to loading screens

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#194]
Add to loading screens that are likely to get "caught" a message so that students (and the teachers who read the messages) know that they should not be waiting for 10 minutes.

For example....

"**Loading data from Flutter**
_This should take less than 1 minutes_" 

.... Etc.

**Comment by SteveFulton95** [comment]
I just hard coded the string "This should take less than 1 minute" where the lodaing data dialogs appeared in commit 27363f351bf16ea537607ab4921dfdaa4b17a4cf.  I don't think that it should ever take longer than that unless a user has a data log that has a lot of points.  Since we now let the user know how many points have been downloaded out of the total number of points, that should not be an issue.
