### ISSUE TITLE
Confirm/clarify desired Pause behavior

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#205]
Sensors only stay paused while you are on the sensors tab. Is that the desired behavior? I can't recall and I was thinking that it stayed paused.

**Comment by lczito** [comment]
I think the original intent was to have a way both to pause the app visual and to pause the outputs if the students were building with everything plugged in, so I think it was supposed to stay paused. This was designed before we had separate tabs and I don't think we ever talked it through completely.

**Comment by ehamner** [comment]
Ok, I would agree with that. Let's switch to behavior where it stays paused until unpaused. 

Related to #190

**Comment by SteveFulton95** [comment]
Do we want this same behavior on the robots tab?

The reason I ask is because when looking into this, I noticed that either @tasota or @pdille added a feature that has to deal with simulating data.  How it works now, is when a page is navigated away from, they reset a flag that determines if the sensor readings are currently streaming or paused.  So I could just remove that block of code, but this would mean if I paused the sensor readings on the sensors tab, it would also cause the simulate data button to be active on the robots page.

**Comment by tasota** [comment]
Yes, so I wasn't tracking this across tabs to avoid confusion in the case that you first pause sensors, then move to the robots tab and want to simulate data. As of now, you can only simulate the same value for all 3 sensors, whereas pausing sensors will "simulate" values at the last position of the sensors before pausing.

So, if we wanted this to go across tabs, would it make sense to show "paused sensors" on the Sensors Tab as being "simulated data" on the Robots Tab? And then I guess vice-versa when simulating data and then going to the Sensors Tab

**Comment by ehamner** [comment]
I have to admit I can't visualize it any more. @tasota will you show it to me in action sometime when you have a chance?

**Comment by jenncross** [comment]
I actually like the current behavior.

Pausing sensors initially was added so that the sensor values would stop moving so that students could briefly record sensor values while doing data recording.

Simulating sensor data on the robot tab was added so that it would be possible to pause the robot during construction and test the motion of the robot at different sensor values. (Please note that if the servo is set to have a frequency, amplitude or cumulative relationship there is no stopping the servos -- as far as I understand.) (It seems difficult -- impossible?--- to do change relationships when simulating.)

I think of these as two very different use cases, that will be more confusing when combined. I like the model of using robot tabs for outputs and sensor tabs for data, which is the model we currently have. It seems cleaner.

**Comment by jenncross** [comment]
Following an in-person conversation, we are going to do a different solution and issues.
