### ISSUE TITLE
Create Wizard for Datalogging

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#253]
Also see #201

**Comment by tasota** [comment]
![imag1398](https://user-images.githubusercontent.com/9115672/41372438-4a8b763a-6f1b-11e8-9fe4-15bdae3b9f2c.jpg)

**Comment by jenncross** [comment]
Here are the three options that we would like to provide as presets: 

- Sample 60 times a minute for 1 minute
- Sample 60 times an hour for 1 hour
- Sample 2 times per hour for 1 day

Thes might need to be two text line buttons?

Or they could be arranged 4 down - 1 across (instead of 2 down - 2 across)
