### ISSUE TITLE
new servo design in wizard?

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#258]
We implemented the new servo design (#196) but the wizard designs are still using the [old indicator](https://app.zeplin.io/project/57f43918d127f7023581eaab/screen/57f43992bcb58ed62c8abb1a).

Should we keep this or replace it with the new servo design?

**Comment by ehamner** [comment]
Parv, Tasota, and I looked at it together.  The way it is working now looks nice when you move the servo slider. And the new servo indicator design would make it harder to indicate a single value, which is what you are doing in the wizard. We said let's leave it how it is for now unless we come up with a strong reason why we should change it.

**Comment by jenncross** [comment]
I wonder if there is a way to make the old indicator (which I agree is nice for picking a single angle) more visually similar to the new indicator. 

So that is obvious for kids that the two representations are very closely related.

Some ideas (I think we should pick a couple of these to implement):

1. Add the center "dot" from the new indicator on the old one
2. Use the green color from the new indicator on the old one
3. Move the 0 and 180 indicators to be inside the circle of the old indicator
4. Make the old indicator a full circle (but gray out the bottom half)

**Comment by tasota** [comment]
Also worth noting that replacing this would mean we do not need #260, so I will just include that issue as dependent on the results of this issue.

**Comment by tasota** [comment]
What we discussed today (@jenncross scans to follow):

- Remove old asset (the half-circle)
- Replace constant green sliver with a green pointer (from old asset)
- Replace the old asset with the new full-circle asset (using the green pointer for value selection)

**Comment by jenncross** [comment]
![img_20180718_145614](https://user-images.githubusercontent.com/11526803/42903685-a51c1fd2-8aa0-11e8-8f73-cf11f186c688.jpg)

**Comment by tasota** [comment]
to be implemented in #265
