### ISSUE TITLE
number of swatch colors to choose from?

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#261]
In the updated layouts on Zeplin there are 12 color swatch choices (see https://app.zeplin.io/project/57f43918d127f7023581eaab/screen/5945c5c0b17e6c221b2cc472) but the original color selector for LED had 14 choices. It appears that the new screen omits the colors: Azure, Chartreuse Green. Did we want to just remove these two color options in all the swatch dialogs?

It's also worth noting that @psdev1 has implemented #113 (advanced color chooser) so more color options do exist now for the user and limiting swatches to 12 instead of 14 allows us to have a 3x4 grid of colors.

**Comment by jenncross** [comment]
It looks like many of those 12 colors offered are the colors from older interface prototypes. They are the more muted/stylized "on-screen" colors that LEDs do not replicate well.  

I would recommend ignoring the colors on that Zeplin image and referring back to #193 for the list of "good" LED colors. Namely:

**On LED**
Color | Red | Green | Blue
-- | -- | -- | --
ROSE | 64 | 0 | 10
RED | 64 | 0 | 0
ORANGE | 64 | 16 | 0
YELLOW | 64 | 55 | 0
CHARTREUSE GREEN | 32 | 64 | 0
GREEN | 0 | 64 | 0
SPRING GREEN | 0 | 64 | 10
CYAN | 0 | 64 | 55
AZURE | 0 | 30 | 64
BLUE | 0 | 0 | 64
VIOLET | 19 | 0 | 64
MAGENTA | 64 | 0 | 64
WHITE | 60 | 64 | 50
BLACK (OFF) | 0 | 0 | 0

We end up with 14 due to the addition of white and black to the 12 RGB primary/secondary/tertiary colors. It is difficult to pick which colors to leave out but my leaning is towards omitting two of the tertiary colors. Violet and Orange seem like important tertiary colors (because of their more important positions in the pigment color space that students learn). Azure and Rose seem a bit repetitive since we already have Blue/Cyan and Red/Magenta. If we wanted to drop one of the two tertiary greens, I think that Spring Green better to omit (Chartreuse is valueable since yellow is so hard to make distinct in RGB).

**Comment by tasota** [comment]
So potentially we omit two of the three colors:

- Azure
- Rose
- Spring Green

Crude screenshot incoming (note blue highlight indicates one of the 3 colors mentioned above). People should cast their votes :-)
<img width="398" alt="screen shot 2018-07-17 at 11 14 48 am 1" src="https://user-images.githubusercontent.com/9115672/42826605-d2450d5a-89b2-11e8-8e2e-43c4b7bd4fde.png">

Also I believe #193 was a global change so we should already be displaying swatch colors that match actual LED intensities better (so yes, we have already modified swatches and won't be using those Zeplin colors).

**Comment by jenncross** [comment]
In that context I actually like Rose.

👎  Azure
👍 Rose
👎 Spring Green

**Comment by tasota** [comment]
I am more or less indifferent in these decisions but I will assess and give my honest opinion below :-)

👎 Azure
👍 Rose
👎 **Green**

(note I think we should remove pure green instead of spring/chartreuse)

**Comment by tasota** [comment]
After discussing with @jenncross and @ehamner we will remove:

- Azure
- Chartreuse Green
