### ISSUE TITLE
Recognize when connection to Flutter is lost / Error screen

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#38]
When the Flutter is unplugged (or bluetooth connection is otherwise lost),  app should provide some notification. enter the offline/no connection/data only mode and not permit further programming until a new connection is made.

**Comment by tasota** [comment]
This is happening but the timeout window is pretty large (like, 10-15 seconds).

To resolve this, someone should look into if it is possible to detect the disconnection sooner.

**Comment by jenncross** [comment]
Screen Design from Molly
![image](https://cloud.githubusercontent.com/assets/11526803/22668109/8e60a86a-ec8d-11e6-9c8b-aaecbf6f7f00.png)

**Comment by ehamner** [comment]
Thanks for all the comments Jenn!!! I was going through my notes as fast 
as I could to try to get things in!

**Comment by pdille** [comment]
Since we're changing BLE modules soon we can ignore this for now, but more discussion is needed for this since I don't think shortening the window is the right solution.

@tasota : Your improvement to the error dialogs around this should suffice until we truly have a proper way to detect a disconnect.

Moving off of Milestone 5.
