### ISSUE TITLE
Implement "Constant" Relationship Type

### ISSUE THREAD

**Issue by tasota** [CMU-CREATE-Lab/flutter-app-android#48]

**Comment by jenncross** [comment]
Protocol Already exists.... 

- Set output
- Request: ‘soutput,value’
- Example: ‘ss1,5a’
- Set servo1 to 90 degrees

Changes will be needed to the link setup dialog ..... only showing one slider/chooser for:
 
- [ ] servo position, 
- [ ] LED color, 
- [ ] buzzer volume,
- [ ] buzzer pitch  

Instead of Min / Max for each

**Comment by jenncross** [comment]
Also NOTE:

When constant relationship is selected, the option to select a sensor is hidden/removed/grayed-out too
