### ISSUE TITLE
Say what sensors were being recorded from

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#65]
In the data table, say what sensors were recording data.

![data-01-filled](https://cloud.githubusercontent.com/assets/24419423/22667263/0eaec6ae-ec8a-11e6-9446-695acf10bce7.png)

**Comment by jenncross** [comment]
Also (not shown in the screen shot), if there is no sensor type set to record - that column of data should be hidden. (Column 3 in the screenshot above)

**Comment by jenncross** [comment]
This might need to be somehow added to the firmware and protocol ... because right now, if the sensor type is changed in the app (before downloading the data). There is no way to retrieve what the sensor type was at the time of recording - only was the current sensor types are.

I will add those labels for now - but please remove if in appropriate.

**Comment by jenncross** [comment]
Probably going to need a firmware change from @JSchapiro  for having this done right.

Though we could assume that the currently set sensor types are correct, for a rough fix.

**Comment by JSchapiro** [comment]
implemented on firmware version 10
