### ISSUE TITLE
Need a way to be able to check what the recording settings are

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#68]
Once recording is set up there is no way to check what the settings are. The teacher can not check if the students did it correctly. Have they set it right before they leave it for the whole weekend? The teacher would like to check. Teacher in pilot one solved this issue by re-configuring the recording herself overnight to make sure they all had a nice long data set.

**Comment by mo11yj** [comment]
In issue #62 I mentioned changing the state on the "Record Data" button. Once this change is made, I think that tapping, "Data Recording" should bring up an editable dialog of the current recording. Zeplin: https://zpl.io/Z1EbcjY. If it is not possible to update the current recording settings let me know and I can do a version that does not have editable fields. If a user makes a change to any of this fields the "OK" text should change to "Update Recording"
![screen shot 2017-02-18 at 9 01 37 pm](https://cloud.githubusercontent.com/assets/25698542/23098525/80be9f7a-f61d-11e6-9221-8d678f3b2346.png)

This is also where a user could cancel the current recording so that they are able to start a new one, I think this flow will make it much more clear that they are stopping a recording to start a new one. Zeplin: https://zpl.io/5BAtQ. 

![screen shot 2017-02-18 at 9 01 47 pm](https://cloud.githubusercontent.com/assets/25698542/23098533/f8a0de18-f61d-11e6-8eb1-41374ebd8e8d.png)

**Comment by ehamner** [comment]
@JSchapiro is it possible to update the recording settings?

I also wonder if kids will read that text about it is currently recording. Maybe we could highlight it by adding an image with it like the light on the board that lights up when it's recording?  ![happy red led](https://cloud.githubusercontent.com/assets/24419423/23177790/24905bce-f836-11e6-9775-8263c52164d4.jpg)

**Comment by JSchapiro** [comment]
the best way to change the recording settings is to stop and start again. the current command set only allows for the user to start a recording session, and stop. If you "update" it by telling it to start a new one, it will overwrite all the old data... if that makes sense

**Comment by jenncross** [comment]
Sounds like updating is not currently possible, which I believe makes the most sense? Since it would be strange to collect in one dataset some data that is collected once per second and then some data that is collected once per day, and then hand graphing it, etc. 

Perhaps the solution would be to have (if you cancel the recording earlier) it ask if you want to immediately download the data you did gather? .... oh! never mind, I see that that is included already in the second screenshot's dialog!

@mo11yj  - I think that means we'll need that other version you mentioned? That does not have editable fields.
