### ISSUE TITLE
Move the servo (or change LED color) as the min/max slider is moved

### ISSUE THREAD

**Issue by ehamner** [CMU-CREATE-Lab/flutter-app-android#78]
When setting a relationship it would help the user if the servo or LED changed as they moved the min/max sliders so they could see what position/color they were choosing. Especially important for the servo.

**Comment by jenncross** [comment]
This seems like a conceptually messy thing to implement, since the mix/max values are in the current model usually only achieved when the min/max sensor values received.

I think it can be done a present using the protocol commands for: 
Set output
   Request: ‘soutput,value’
   Example: ‘ss1,5a’
   Set servo1 to 90 degrees

But there will be cognitive dissonance when the light you just set to be pink or blue suddenly becomes purple when the relationship with the sensor is actually applied.

This might be good to address as part of #53 when looking at how to simulate sensor values for testing the output ranges. Or ask Molly to work on a solution for, since it would be a substantial addition to the interaction process for making relationships. 

Might also be worth pushing back to March?

**Comment by tasota** [comment]
It certainly won't be able to do it in a fluid motion. At best, you could probably drag the value, and when you release it, then the (constant) value can be set on the output.

**Comment by ehamner** [comment]
Re: Mike's comment, that's how it works on Hummingbird/CREATE Lab Visual Programmer and it's good enough.

**Comment by jenncross** [comment]
Ok, this can be solved as part of issue #197 

While the link wizard is in the state for setting the output endpoints, use the "blocks style" control to make the servo, LEDs or buzzer to match the wizard slider setting. (Updating infrequently / when the slider is "released" is OK!)
