### ISSUE TITLE
Replace "wind speed" sensor icon in the sensor icon menu with new "air quality" sensor option

### ISSUE THREAD

**Issue by jenncross** [CMU-CREATE-Lab/flutter-app-android#81]

**Comment by lczito** [comment]
This can replace the "wind speed" icon in the sensor icon menu

**Comment by jenncross** [comment]
Note: The sensor detects particulates(dust, pollen, pollution) in the air, so our current idea involves a cluster of dots representing the particles in the air.

**Comment by ehamner** [comment]
If this gets added in sooner, that's great. But Pilot 2 is focused on sound, light, and distance so I changed it to Release 3.

**Comment by mo11yj** [comment]
Hey guys, I have two different ideas for the Air Quality sensor, let me know which you prefer and I can make sure all the assets are there. 

![screen shot 2017-02-18 at 9 50 16 pm](https://cloud.githubusercontent.com/assets/25698542/23098742/51ef9b7a-f624-11e6-99b2-54163b79ffcc.png)

**Comment by ehamner** [comment]
I had to share Katie's interpretation: books with steam coming out and acorns or snow. : )
(After a more in depth conversation about air quality sensors and how particulate sensors sense dust in the air she said that the one with the dots looks like it's sensing dust and the one on the left looks like it's sensing smoke.)

There was also a conversation last week about maybe calling it a Particulate Sensor, so that a higher number would more clearly relate to more particulates. Where as now a higher number is lower air quality, which could be confusing.

**Comment by mo11yj** [comment]
Thats hilarious, I definitely wasn't going for burning books :) 

I will go with the second version and get those assets added to Zeplin.

**Comment by mo11yj** [comment]
https://zpl.io/Z2lnsNY

Air Quality icon added to the icons page in Zeplin

**Comment by pdille** [comment]
@mo11yj: Looks like the grey version of this icon is missing from Zeplin.

**Comment by pdille** [comment]
Addressed in commit 4e698fc7
